# Load required imports

In [206]:
import numpy as np
import tensorflow as tf

# Create training
## Step-1: Create train dataset which we will use to train on operations
## 87 + 50, 87 - 50, 87 * 50, 87 / 50
##### [[87 50]
##### [65 84]
##### ...
##### [74 54]
##### [72 86]
##### [72 41]]
## Step-2: create dataset to represent +,-,*,/, as we have different operations +,-,*,/.
## We can not directly use these, we use one-hot encoding
## Step-3: Combine Step-1, Step-2 to create actual training dataset

In [207]:
num_of_samples = 21000
# Step - 1
train_dataset =  np.random.randint(1, 100, (num_of_samples, 2))
train_dataset = train_dataset
print(f"train dataset shape: {train_dataset.shape}")

# Step-2
operations_dateset = np.tile([0, 1, 2], 7000)
print(operations_dateset)
print(f"operation dateset shape: {operations_dateset.shape}")
# One hat encoding
one_hot_operations_dateset = np.eye(4)[operations_dateset]
print(one_hot_operations_dateset)
print(f"one_hot_operations_dateset shape: {one_hot_operations_dateset.shape}")

# Step -3
final_train_dataset = np.concatenate([train_dataset, one_hot_operations_dateset], axis=1)
print(f"final train_dataset shape: {final_train_dataset.shape}")

train dataset shape: (21000, 2)
[0 1 2 ... 0 1 2]
operation dateset shape: (21000,)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
one_hot_operations_dateset shape: (21000, 4)
final train_dataset shape: (21000, 6)


# Creating Test dataset
## we loop through number of samples and operations
## find the result and append to test dataset
## Convert to array

In [208]:
test_dataset = []
addition_sample_count = 0
subtraction_sample_count = 0
multiplication_sample_count = 0
division_sample_count = 0
for i in range(num_of_samples):
    input_one, input_two = train_dataset[i]
    operation_type = operations_dateset[i]
    if operation_type == 0:
        test_dataset.append(input_one + input_two)
        addition_sample_count +=1
    elif operation_type == 1:
        test_dataset.append(input_one - input_two)
        subtraction_sample_count +=1
    else:
        test_dataset.append(input_one * input_two)
        multiplication_sample_count +=1

    # elif operation_type == 1:
    #     test_dataset.append(input_one - input_two)
    #     subtraction_sample_count +=1
    # elif operation_type == 2:
    #     test_dataset.append(input_one * input_two)
    #     multiplication_sample_count +=1
    # else:
    #     test_dataset.append(input_one / input_two)
    #     division_sample_count +=1

test_dataset = np.array(test_dataset)
test_dataset = test_dataset
print(f"test_dataset shape: {test_dataset.shape}")
print(f"addition sample count: {addition_sample_count}")
print(f"subtraction sample count: {subtraction_sample_count}")
print(f"multiplication sample count: {multiplication_sample_count}")
print(f"division sample count: {division_sample_count}")

test_dataset shape: (21000,)
addition sample count: 7000
subtraction sample count: 7000
multiplication sample count: 7000
division sample count: 0


# Creating model
## Input shape
### [input_one, input_two, +, -, *, /]
### 6x1 shape

In [209]:
number_of_hidden_layers = 50
number_of_outputs = 1
math_operation_model = tf.keras.Sequential([
    tf.keras.layers.Dense(number_of_hidden_layers, activation=tf.nn.relu, input_shape=(6,)),
    tf.keras.layers.Dense(number_of_hidden_layers, activation=tf.nn.relu),
    tf.keras.layers.Dense(number_of_outputs),
])

# Adding optimizer and loss function

In [210]:
math_operation_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    loss=tf.keras.losses.mse,
    metrics=['mae']
)

# Training model

In [211]:
epochs_size = 100
math_operation_model.fit(
    x=final_train_dataset,
    y=test_dataset,
    epochs=epochs_size,
    verbose=2,
    batch_size=40,
    shuffle=True
)

Epoch 1/100
525/525 - 1s - 3ms/step - loss: 2849869.7500 - mae: 1024.2617
Epoch 2/100
525/525 - 1s - 1ms/step - loss: 2491726.2500 - mae: 1154.9606
Epoch 3/100
525/525 - 1s - 1ms/step - loss: 2436036.2500 - mae: 1135.3276
Epoch 4/100
525/525 - 1s - 2ms/step - loss: 2352249.0000 - mae: 1112.2878
Epoch 5/100
525/525 - 1s - 1ms/step - loss: 2217715.2500 - mae: 1064.0583
Epoch 6/100
525/525 - 1s - 1ms/step - loss: 1980913.3750 - mae: 983.4894
Epoch 7/100
525/525 - 1s - 2ms/step - loss: 1579337.5000 - mae: 843.7482
Epoch 8/100
525/525 - 1s - 1ms/step - loss: 1094974.7500 - mae: 677.9187
Epoch 9/100
525/525 - 1s - 1ms/step - loss: 772601.8125 - mae: 563.6332
Epoch 10/100
525/525 - 1s - 1ms/step - loss: 597888.1250 - mae: 495.1884
Epoch 11/100
525/525 - 1s - 1ms/step - loss: 482252.3750 - mae: 443.4480
Epoch 12/100
525/525 - 1s - 1ms/step - loss: 392978.1562 - mae: 396.9280
Epoch 13/100
525/525 - 1s - 1ms/step - loss: 323803.5625 - mae: 355.0562
Epoch 14/100
525/525 - 1s - 1ms/step - loss: 26

# Predict value

In [215]:
math_operation_model.predict(np.array([[8, 4, 0, 0, 1, 0,]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[45.51742]], dtype=float32)