# import numpy as np

In [3]:
import numpy as np

# Scalar

In [4]:
s = 408
s

408

# Vector

In [5]:
v = np.array([4, 0, 8])
v

array([4, 0, 8])

# Matrix

In [6]:
m = np.array([[4, 0, 8],[5, 0, 8]])
m

array([[4, 0, 8],
       [5, 0, 8]])

# Datatype

In [7]:
print(type(s))
print(type(v))
print(type(m))

<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
print(v.shape)
print(m.shape)

(3,)
(2, 3)


# Creating Tensor

In [9]:
m1 = np.array([[1, 2, 3],[4, 5, 6]])
m2 = np.array([[7, 8, 9], [10, 11, 12]])
t = np.array([m1, m2])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
shape_of_t = t.shape
shape_of_t

(2, 2, 3)

# addition of matricis

In [11]:
sum_of_two = m1 + m2
sum_of_two

array([[ 8, 10, 12],
       [14, 16, 18]])

In [12]:
substraction_of_two = m1 - m2
substraction_of_two

array([[-6, -6, -6],
       [-6, -6, -6]])

# Transpose matrix

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# Dot Product

In [16]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.dot(x,y)

np.int64(32)

# Scalar * Scalar

In [17]:
np.dot(4 , 8)

np.int64(32)

# Scalar * Vector

In [18]:
c = np.array([1, 2, 3])
4 * c

array([ 4,  8, 12])