# Under fitting and Over fitting
## Under fitting: is when a model is too simple to capture the underlying patterns in the data, leading to poor performance on both training and test datasets.
## Over fitting, on the other hand, occurs when a model is too complex and captures noise in the training data as if it were a true pattern, resulting in excellent performance on the training data but poor generalization to new, unseen data.
## Over fitting can be mitigated through techniques such as cross-validation, regularization, splitting and pruning, while under fitting can be addressed by increasing model complexity or adding more relevant features.

# Over fitting can be minimized using train-test split
# split the dataset into a training set and a testing set. The training set is used to train the model, while the testing set is used to evaluate its performance on unseen data. This helps to ensure that the model generalizes well and does not overfit to the training data.

# Import the relevant libraries

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

# Create a sample dataset

In [4]:
data_set_one = np.arange(1, 101)
data_set_one

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
data_set_two = np.arange(501, 601)
data_set_two

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

# Split the dataset into training and testing sets

In [6]:
train_test_split(data_set_one)

[array([  4,  56,  93,  58,  31,  19,  10,  21,  29,  48, 100,  55,  54,
         47,  88,  51,  57,  18,  44,  41,   3,  22,  63,  85,  79,  45,
         43,  87,  96,   8,  60,  28,  66,  83,  15,   7,  32,  64,  59,
          9,  97,  20,  42,  38,  39,  17,   6,  27,  12,  53,  75,  67,
         92,  77,  13,  25,  76,  68,  69,   2,  89,  23,  61,  73,  72,
         40,  52,  34,  35,  11,  71,  82,  46,  78,  94]),
 array([ 1, 65, 95, 50, 99, 70, 98, 16, 14, 24, 91, 62, 90,  5, 86, 33, 30,
        26, 74, 81, 37, 80, 49, 84, 36])]

# By default, the train_test_split function splits the data into 75% training and 25% testing sets. You can adjust this ratio using the test_size or train_size parameters.

In [17]:
data_set_one_train, data_set_one_test= train_test_split(data_set_one, test_size=0.2, random_state=42)

# Display the training and testing sets

In [18]:
data_set_one_train.shape, data_set_one_test.shape

((80,), (20,))

In [19]:
data_set_one_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [22]:
data_set_one_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

# We can also split multiple datasets simultaneously, ensuring that the corresponding samples are kept together in the training and testing sets. This is particularly useful when you have features and labels that need to be split in a consistent manner.

In [24]:
data_set_one_train, data_set_one_test, data_set_two_train, data_set_two_test = train_test_split(data_set_one, data_set_two, test_size=0.2, random_state=42)

# Shape of the training and testing sets

In [27]:
(data_set_one_train.shape, data_set_one_test.shape, data_set_two_train.shape
     , data_set_two_test.shape)

((80,), (20,), (80,), (20,))

In [28]:
data_set_two_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [29]:
data_set_two_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])